# Generated by Django 4.2.6 on 2023-10-05 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_shape_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=255)),
                ('Space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.space')),
                ('restaurants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.restaurant')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.shape')),
            ],
        ),
    ]
