# Generated by Django 4.2.6 on 2023-10-05 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0006_temporder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporder',
            name='mac',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='temporder',
            name='menu_item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.menuitem'),
        ),
    ]
