# Generated by Django 4.2.6 on 2023-10-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0007_alter_temporder_mac_alter_temporder_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='mac',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='menu_item',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
