# Generated by Django 4.2.5 on 2023-10-07 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0009_alter_order_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tableNo',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.brtable'),
        ),
    ]
