# Generated by Django 4.2.5 on 2023-10-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0010_alter_order_tableno'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='docNo',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
