# Generated by Django 4.2.5 on 2023-10-07 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0011_order_docno'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNo', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.brtable')),
            ],
        ),
    ]
