# Generated by Django 4.2.5 on 2023-10-07 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0012_orderinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.orderinfo'),
        ),
    ]
