# Generated by Django 4.2.5 on 2023-10-07 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0013_order_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='docNo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurant.orderinfo'),
        ),
    ]
