# Generated by Django 4.2.5 on 2023-10-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0014_orderinfo_docno_alter_order_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='cookOrder',
            field=models.BooleanField(default=False),
        ),
    ]
