# Generated by Django 4.0.10 on 2023-10-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0017_brtable_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.PositiveIntegerField()),
            ],
        ),
    ]
